name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Code style check
        run: ./vendor/bin/phpcs --standard=PSR12 ./src

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --level=7
