name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: xdebug
          coverage: xdebug
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        continue-on-error: true

      - name: Upload coverage.xml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload coverage report to Scrutinizer API
        run: |
          curl -X POST --data-binary @coverage.xml \
          -H "Authorization: Bearer ${{ secrets.SCRUTINIZER_API_KEY }}" \
          -H "Content-Type: text/xml" \
          "https://scrutinizer-ci.com/api/repositories/g/jidaikobo-shibata/log/coverage"
